# Generated by Django 3.1.7 on 2021-02-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210227_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='students',
            field=models.ManyToManyField(to='accounts.Student'),
        ),
    ]
