# Generated by Django 3.1.7 on 2021-02-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210227_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='exercises',
            field=models.ManyToManyField(to='accounts.Exercise'),
        ),
    ]
