# Generated by Django 3.1.7 on 2021-02-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210227_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
