# Generated by Django 3.1.7 on 2021-02-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='file',
            field=models.FileField(null=True, upload_to='accounts/media/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
