# Generated by Django 3.1.7 on 2021-02-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210228_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='update',
        ),
    ]
