# Generated by Django 3.1.7 on 2021-02-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_exercise_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='file',
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='No Upload', null=True, upload_to='accounts/media/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('exercise_sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.exercise')),
                ('student_sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student')),
            ],
        ),
    ]
