# Generated by Django 3.1.7 on 2021-02-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210228_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='exercise_sub',
            new_name='exercisesub',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='student_sub',
            new_name='studentsub',
        ),
    ]
