# Generated by Django 3.1.7 on 2021-03-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210228_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='mark',
            field=models.IntegerField(null=True),
        ),
    ]
