# Generated by Django 3.1.7 on 2021-03-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_solution_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
