# Generated by Django 3.1.7 on 2021-03-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210307_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='exercisesub',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='studentsub',
            new_name='student',
        ),
    ]
